image: gitpod/workspace-mongodb

tasks:
  - name: Install Deps
    before: >
      gp open README.md &&
      gp open src/features/syngrisi/basic_example.feature
    init: >
      sudo apt-get update &&
      sudo apt-get install -y libgbm-dev &&
      sudo apt-get install -yq --no-install-recommends libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3 &&
      npm i &&
      gp sync-done install &&
      exit 0
    openMode: split-right
  - name: Start Mongo
    init: gp sync-await install
    command: >
      mkdir -p /workspace/data && 
      mongod --dbpath /workspace/data &
      gp sync-done mongo && 
      exit 0
    openMode: split-right
  - name: Start Syngrisi
    init: gp sync-await mongo
    command: npx sy
    openMode: split-right

#  - name: Chromedriver
#    init: gp sync-await install
#    command: npx chromedriver --port=9950
#  - init: 'echo "Starting MongoDB" && mongod --fork --logpath /tmp/mongod.log'
ports:
  - name: Syngrisi
    port: 3000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: true

vscode:
  extensions:
    - stateful.runme
#    - alexkrechik.cucumberautocomplete
#    - CucumberOpen.cucumber-official




