image: gitpod/workspace-mongodb

tasks:
  - init: 'mkdir -p /workspace/data && mongod --dbpath /workspace/data'
  - init: 'npm i'
    command: 'npx sy'
#  - init: 'echo "Starting MongoDB" && mongod --fork --logpath /tmp/mongod.log'
ports:
  - port: 3000
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: true

