image: gitpod/workspace-mongodb

tasks:
  - name: Install Deps
    init: npm i && npx @puppeteer/browsers install chrome@118.0.5993.0 && sudo apt-get install -y libgbm-dev &&  gp sync-done install
  - name: Start Mongo
    init: gp sync-await install
    command: >
      mkdir -p /workspace/data && 
      mongod --dbpath /workspace/data &
      gp sync-done mongo
  - name: Start Syngrisi
    init: gp sync-await mongo
    command: npx sy
  - name: Chromedriver
    init: gp sync-await install
    command: npx chromedriver --port=9950
#  - init: 'echo "Starting MongoDB" && mongod --fork --logpath /tmp/mongod.log'
ports:
  - port: 3000
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: true

