image: gitpod/workspace-mongodb

tasks:
  - name: 'Mongo'
    init: 'mkdir -p /workspace/data && mongod --dbpath /workspace/data &'
  - name: 'Install'
    init: 'npm i'
  - name: 'Syngrisi'
    init: gp sync-await bundle
    command: 'npx sy'
  - name: 'Chromedriver'
    init: gp sync-await bundle
    command: 'npx chromedriver --port=9950'
#  - init: 'echo "Starting MongoDB" && mongod --fork --logpath /tmp/mongod.log'
ports:
  - port: 3000
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: true

